### ISSUE TITLE
Nginx with Docker in setup

### ISSUE THREAD

**Issue by jgwerner** [rgbkrk/jupyterhub-compmodels-deploy#1]
Hi, was curious, any particular reason you have Nginx running in a Docker container? Was guessing that may have been done to simplify playbook, but wanted to get your feedback.

**Comment by rgbkrk** [comment]
It makes the deployment a little bit simpler, but there's a bigger reason.

The static files are being [served by nginx, mounted straight from a docker container](https://github.com/rgbkrk/jupyterhub-compmodels-deploy/blob/d3da0fd17e34ca9462012a2d64adeba2e170693e/roles/proxy/tasks/main.yml#L8-L10):

``` yaml
# Get static resources from the userland container
- name: static files container
  docker:
    image: jupyter/systemuser
    state: running
    name: static-files
    command: echo "#data-container-hack"
    volumes:
    - "{{ notebook_static_files }}"
  tags:
    - docker-rebuild

...

- name: launch nginx
  docker:
    image: nginx
    state: running
    name: nginx
    volumes: "{{ nginx_volumes }}"
    ports: "{{ nginx_ports }}"
    volumes_from:
    - static-files      # Make sure static files are synced up with user land container
```

Do you have to do it this way? Not at all. You could run the JupyterHub setup on one node, doing TLS/SSL termination with JupyterHub and launching notebook servers on all the same machine.
